require('dotenv').config()
const express = require('express')
const cors = require('cors')
const app = express()

const port = 3000
app.use(cors())
app.use(express.json())

const usuariosRouter = require('./routes/usuario.routes');
const authRouter = require('./routes/auth.routes')
const paisRouter = require('./routes/pais.routes')
const ciudadRouter = require('./routes/ciudad.routes')
const sexoRouter = require('./routes/sexo.routes')
const razonSocialRouter = require('./routes/razonSocial.routes')
const condicionFiscalRouter = require('./routes/condicionFiscal.routes')
const clienteRouter = require('./routes/cliente.routes')
const cargoRouter = require('./routes/cargo.routes')
const empleadoRouter = require('./routes/empleado.routes')
const barcoRouter = require('./routes/barco.routes')
const categoriaCargaRouter = require('./routes/categoriaCarga.routes')
const containerEstadoRouter= require('./routes/containerEstado.routes')
const containerRouter = require('./routes/container.routes')
const puertoRouter= require('./routes/puerto.routes')
const viajeEstadoRouter= require('./routes/viajeEstado.routes')
const viajeRouter= require('./routes/viaje.routes')
const reservaEstadoRouter= require('./routes/reservaEstado.routes')
const reservaRouter= require('./routes/reserva.routes')
const servicioAgregadoRouter= require('./routes/servicioAgregado.routes')
const facturaEstadoRouter= require('./routes/facturaEstado.routes')
const impuestoRouter= require('./routes/impuesto.routes')
const medioPagoRouter= require('./routes/medioPago.routes')
const facturaRouter= require('./routes/factura.routes')
const pagoRouter= require('./routes/pago.routes')
const remitoRouter= require('./routes/remito.routes')
const viajeContainerRouter= require('./routes/viajeContainer.routes')
const viajeEmpleadoRouter= require('./routes/viajeEmpleado.routes')
const reservaViajeRouter=require('./routes/reservaViaje.routes')
const reservaServicioRouter=require('./routes/reservaServicios.routes')
const facturaImpuestoRouter= require('./routes/facturaimpuesto.routes')
const cargaCointainerRouter = require('./routes/cargaContainer.routes')

app.use('/usuario', usuariosRouter)
app.use('/auth', authRouter)
app.use('/pais', paisRouter)
app.use('/ciudad', ciudadRouter)
app.use('/sexo', sexoRouter)
app.use('/razonsocial', razonSocialRouter)
app.use('/condicionfiscal', condicionFiscalRouter)
app.use('/cliente', clienteRouter)
app.use('/cargo', cargoRouter)
app.use('/empleado', empleadoRouter)
app.use('/barco', barcoRouter)
app.use('/categoriacarga', categoriaCargaRouter)
app.use('/containerestado', containerEstadoRouter)
app.use('/container', containerRouter)
app.use('/puerto', puertoRouter)
app.use('/viajeestado', viajeEstadoRouter)
app.use('/viaje', viajeRouter)
app.use('/reservaestado', reservaEstadoRouter)
app.use('/reserva', reservaRouter)
app.use('/servicioagregado', servicioAgregadoRouter)
app.use('/facturaestado', facturaEstadoRouter)
app.use('/impuesto', impuestoRouter)
app.use('/mediopago', medioPagoRouter)
app.use('/factura', facturaRouter)
app.use('/pago', pagoRouter)
app.use('/remito', remitoRouter)
app.use('/viajecontainer', viajeContainerRouter)
app.use('/viajeempleado', viajeEmpleadoRouter)
app.use('/reservaviaje', reservaViajeRouter)
app.use('/reservaservicio', reservaServicioRouter)
app.use('/facturaimpuesto', facturaImpuestoRouter)
app.use('/cargacontainer', cargaCointainerRouter)

app.listen(port, () => {
    console.log(`servidor corriendo en localhost:${port}`)
})  